## Exercise 1: NumPy Array Indexing and Slicing

Create a random NumPy array of five rows and four columns. Using array indexing and slicing, display the items from row three to end and column two to end.

In [6]:
import numpy as np

randomArray = np.random.randint(1, 10, size=(5, 4))
print("Array:")
print(randomArray)

slicedRandomArray = randomArray[2:, 1:]
print("Array from row three to end and column two to end")
print(slicedRandomArray)

Array:
[[4 6 3 2]
 [1 1 2 4]
 [3 8 9 8]
 [2 6 1 6]
 [1 8 6 3]]
Array from row three to end and column two to end
[[8 9 8]
 [6 1 6]
 [8 6 3]]


## Exercise 2: Perfect Number Function

An integer, _n_, is said to be _perfect_ when the sum of all of the proper divisors of _n_ is equal to _n_. For example, 28 is a perfect number because its proper divisors are 1, 2, 4, 7 and 14, and 1+2+4+7+14=28.

Write a function that determines whether or not a positive integer is perfect. Your function will take one parameter. If that parameter is a perfect number then your function will return True, otherwise it will return False.

In [8]:
def is_perfect_number(number):
  sum_of_divisors = 0

  for i in range(1, number):
    if number % i == 0:
      sum_of_divisors += i

  return sum_of_divisors == number

test_numbers = [28, 10, 20, 18]

for number in test_numbers:
  print("For number : " + str(number) + " the result is : " + str(is_perfect_number(number)))

For number : 28 the result is : True
For number : 10 the result is : False
For number : 20 the result is : False
For number : 18 the result is : False


## Exercise 3: Text Formatting Class

Create a class with the following methods:

- Constructor (`__init__`) – This method should take the argument `text`, make it lower case, and remove all punctuation. Assume only the following punctuation is used: period, exclamation mark, comma and question mark. Assign this newly formatted text to a new attribute called `fmtText`.
- `strLength` – This method should return the length of the text.

In [11]:
class TextFormatter:
  def __init__(self, text):
    text = text.lower()

    for semn in [".", "!", ",", "?"]:
      text = text.replace(semn, "")

    self.frmText = text

  def strLength(self):
    return len(self.frmText)


test_text = "Hello, World! This is a text. What do you think?"

formatter = TextFormatter(test_text)

formatted_text = formatter.frmText
print("Formatted text: " + formatted_text)

length = formatter.strLength()
print("Length of the text: " + str(length))

Formatted text: hello world this is a text what do you think
Length of the text: 44
