# Exercitiul 1

Create tensors of the following ranks: 1, 2, and 3. Use values between 0 and 1 to fill your tensors. The size of the tensors can be defined as you wish, given that the ranks are created correctly. Print the shape of each of the tensors using the shape property.

In [6]:
import torch

# in acest caz -> generam un vector pe o linie cu 3 coloane
tensorRankOne = torch.rand(3)

print(tensorRankOne)
print(tensorRankOne.shape)

# primul parametru -> linii, al doilea -> coloane
tensorRankTwo = torch.rand(2, 3)

print(tensorRankTwo)
print(tensorRankTwo.shape)

tensorRankThree = torch.rand(2, 3, 4)

print(tensorRankThree)
print(tensorRankThree.shape)

tensor([0.5060, 0.5718, 0.8116])
torch.Size([3])
tensor([[0.4467, 0.2327, 0.5769],
        [0.7881, 0.1514, 0.5303]])
torch.Size([2, 3])
tensor([[[0.2123, 0.9487, 0.7703, 0.2743],
         [0.1048, 0.7321, 0.1243, 0.5276],
         [0.4235, 0.3657, 0.6772, 0.8061]],

        [[0.7058, 0.3222, 0.3643, 0.0976],
         [0.4210, 0.8492, 0.8678, 0.4168],
         [0.9398, 0.5530, 0.7147, 0.4316]]])
torch.Size([2, 3, 4])


# Exercitiul 2

The sigmoid activation function is an essential function in neural networks and is defined as follows:$$\text{sigmoid}(x) = \frac{1}{1 + e^{-x}}$$Take the derivative of this function with respect to $x$, where $x = [-10, 10, 8]$.

In [15]:
def sigmoid(x):
  return 1 / (1 + torch.exp(-x))

x = torch.tensor([-10.0, 10.0, 8.0], requires_grad = True)

y = sigmoid(x)

y.backward(torch.ones_like(x))

print("Derivative of sigmoid at x = ", x.tolist(), " is ", x.grad.tolist())

# sau mai putem face

x = torch.tensor([-10.0, 10.0, 8.0], requires_grad = True)

y = sigmoid(x)

y.sum().backward()

print("Derivative of sigmoid at x = ", x.tolist(), " is ", x.grad.tolist())

Derivative of sigmoid at x =  [-10.0, 10.0, 8.0]  is  [4.5395812776405364e-05, 4.539580550044775e-05, 0.0003352376807015389]
Derivative of sigmoid at x =  [-10.0, 10.0, 8.0]  is  [4.5395812776405364e-05, 4.539580550044775e-05, 0.0003352376807015389]


# Exercitiul 3

Define the following two matrices:

$$A = \begin{bmatrix} 1 & 2 & -3 \\ 4 & 5 & 10 \end{bmatrix}, B = \begin{bmatrix} 10 & 11 & -2 \\ 13 & -3 & 8 \end{bmatrix}$$
calculate the Hadamard product of the two matrices;add the scalar $a = 10$ to each element of matrix $B$;print the transpose of both matrices.

In [18]:
A = torch.tensor(
    [
        [1, 2, -3],
        [4, 5, 10]
    ]
)

B = torch.tensor(
    [
        [10, 11, -2],
        [13, -3, 8]
    ]
)

hadamardProduct = A * B

print("Hadamard Product is : ", hadamardProduct)

a = 10

B_new = B + a

print("B_new is : ", B_new)

print("Transpose of A is : ", A.T)
print("Transpose of B is : ", B.T)

Hadamard Product is :  tensor([[ 10,  22,   6],
        [ 52, -15,  80]])
B_new is :  tensor([[20, 21,  8],
        [23,  7, 18]])
Transpose of A is :  tensor([[ 1,  4],
        [ 2,  5],
        [-3, 10]])
Transpose of B is :  tensor([[10, 13],
        [11, -3],
        [-2,  8]])


# Exercitiul 4

Create the following two matrices:$$A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}, B = \begin{bmatrix} 10 & 11 \\ -2 & 0 \\ 1 & -3 \end{bmatrix}$$Multiply the two matrices and compute the Frobenius norm of $A$ and $B$.

In [24]:
A = torch.tensor(
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    dtype = torch.float32
)

B = torch.tensor(
    [
        [10, 11],
        [-2, 0],
        [1, -3]
    ],
    dtype = torch.float32
)

product = torch.mm(A, B)

print("Product of matrix A and B is : ", product)

frobeniusNormA = torch.norm(A, p = "fro")
frobeniusNormB = torch.norm(B, p = "fro")

print("Frobenius norm of A : ", frobeniusNormA.item())
print("Frobenius norm of B : ", frobeniusNormB.item())

Product of matrix A and B is :  tensor([[ 9.,  2.],
        [36., 26.]])
Frobenius norm of A :  9.539392471313477
Frobenius norm of B :  15.329710006713867
