In [27]:
import torch

x = torch.randn(1)
print(x.shape)

y = torch.randn(1, 2)
print(y.shape)

z = torch.randn(1, 2, 3)
print(z.shape)

torch.Size([1])
torch.Size([1, 2])
torch.Size([1, 2, 3])


In [30]:
def sigmoid(x):
    return 1 / (1 + torch.exp(-x))


x = torch.tensor([-10.0, 10.0, 8.0], requires_grad=True)
print(x)

y = sigmoid(x)
print(y)

y.sum().backward()
print(x.grad)

analityc_derivative = sigmoid(x) * (1 - sigmoid(x))
print(analityc_derivative)

tensor([-10.,  10.,   8.], requires_grad=True)
tensor([4.5398e-05, 9.9995e-01, 9.9966e-01], grad_fn=<MulBackward0>)
tensor([4.5396e-05, 4.5396e-05, 3.3524e-04])
tensor([4.5396e-05, 4.5417e-05, 3.3522e-04], grad_fn=<MulBackward0>)


In [ ]:
a = torch.tensor([[1, 2, -3], [4, 5, 10]])
b = torch.tensor([[10, 11, -2], [13, -3, 8]])

hadamard_product = a * b
print(hadamard_product)

b += 10
print(b)

print(a.T)
print(b.T)

tensor([[ 10,  22,   6],
        [ 52, -15,  80]])
tensor([[20, 21,  8],
        [23,  7, 18]])
tensor([[ 1,  4],
        [ 2,  5],
        [-3, 10]])
tensor([[20, 23],
        [21,  7],
        [ 8, 18]])


In [23]:
a = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
b = torch.tensor([[10.0, 11.0], [-2.0, 0.0], [1.0, -3.0]])

matrix_mul = a @ b  # a.mm(b)
print(matrix_mul)

frobenius_norm_a = torch.norm(a)
frobenius_norm_b = torch.norm(b)
print(frobenius_norm_a)
print(frobenius_norm_b)

tensor([[ 9.,  2.],
        [36., 26.]])
tensor(9.5394)
tensor(15.3297)
