# Exercitiul 1

In [ ]:
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

In [ ]:
X, y = make_regression(
    n_samples = 1000,
    n_features = 1,
    noise = 0.1,
    bias = 1,
    random_state = 42
)

y = y**2

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size = 0.2,
                                                    random_state = 42)

In [ ]:
DEGREE = 2

In [ ]:
poly_features = PolynomialFeatures(degree = DEGREE,
                                   include_bias=False)

X_poly = poly_features.fit_transform(X_train)

lin_reg = LinearRegression()
lin_reg.fit(X_poly, y_train)

LinearRegression()

In [ ]:
lin_reg.coef_, lin_reg.intercept_ , mean_squared_error(y_test, lin_reg.predict(poly_features.fit_transform(X_test)))

(array([ 33.60683495, 280.35038194]),
 np.float64(1.1397772354312679),
 11.548416287060846)

# Exercitiul 2

In [ ]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
import numpy as np

In [ ]:
X, y = make_classification(
    n_samples=1000,
    n_features=4,
    n_informative=4,
    n_redundant=0,
    n_classes=3,
    n_clusters_per_class=1,
    random_state=42,
)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size = 0.25,
                                                    random_state = 42)

In [ ]:
DEGREE = 3
COEFFICIENT = 1
hyperparamC = 10
EPOCHS = 10000

In [ ]:
poly_kernel_svm_clf = Pipeline([
        ("scaler", StandardScaler()),
        ("svm_clf", SVC(kernel = "poly",
                        degree = DEGREE,
                        coef0 = COEFFICIENT,
                        C = hyperparamC,
                        max_iter = EPOCHS,
                        probability=True,
                        random_state= 42))
    ])

poly_kernel_svm_clf.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('svm_clf',
                 SVC(C=10, coef0=1, kernel='poly', max_iter=10000,
                     probability=True, random_state=42))])

In [ ]:
poly_kernel_svm_clf[1].support_vectors_[2]

array([-0.64597123, -0.38253777, -0.14682131,  0.58908964])

In [ ]:
accuracy = poly_kernel_svm_clf.score(X_test, y_test)
accuracy

0.908

In [ ]:
y_pred = poly_kernel_svm_clf[1].predict_proba(X_test)
y_pred[8]

array([0.44872087, 0.5438004 , 0.00747872])

# Exercitiul 3

In [ ]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [ ]:
X, y = make_classification(
    n_samples=1000,
    n_features=4,
    n_informative=4,
    n_redundant=0,
    n_classes=3,
    n_clusters_per_class=1,
    random_state=42,
)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size = 0.25,
    random_state = 42
)

In [ ]:
MAX_DEPTH = 2

tree_clf = DecisionTreeClassifier(max_depth= MAX_DEPTH, random_state=42)

tree_clf.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=2, random_state=42)

In [ ]:
feature_importances = tree_clf.feature_importances_
accuracy = accuracy_score(y_test, tree_clf.predict(X_test))
feature_importances, accuracy, tree_clf.predict_proba(X_test)[7]

(array([0.        , 0.18279047, 0.42899456, 0.38821497]),
 0.78,
 array([0.08943089, 0.16260163, 0.74796748]))

# Exercitiul 4

In [ ]:
from sklearn.datasets import make_circles
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
import numpy as np

In [ ]:
X, y = make_circles(
    n_samples = 1000,
    factor = 0.1,
    noise = 0.01,
    random_state = 42
)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size = 0.25,
                                                    random_state = 42
                                                    )

In [ ]:
pca = PCA(n_components=0.95)

X_train_reduced = pca.fit_transform(X_train)

In [ ]:
pca.n_components_, pca.components_, pca.explained_variance_ratio_

(np.int64(2),
 array([[ 0.76930085, -0.63888669],
        [ 0.63888669,  0.76930085]]),
 array([0.50537804, 0.49462196]))

In [ ]:
X_test_pca = pca.fit_transform(X_test)
sample_8_inversed = pca.inverse_transform(X_test_pca)[7]
sample_8_inversed

array([0.98931132, 0.18834881])

# Exercitiul 5

In [ ]:
from sklearn.datasets import make_circles
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

In [ ]:
X, y = make_circles(
    n_samples=1000,
    factor=0.5,
    noise=0.1,
    random_state=42,
)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size = 0.25,
                                                    random_state = 42)

In [ ]:
kmeans_iter = KMeans(n_clusters = 5,
                     init = "random",
                     algorithm = "lloyd",
                     max_iter = 10,
                     random_state = 42)

kmeans_iter.fit(X_train)

KMeans(init='random', max_iter=10, n_clusters=5, random_state=42)

In [ ]:
y_pred = kmeans_iter.predict(X_test)
y_pred[4], kmeans_iter.cluster_centers_[2], kmeans_iter.inertia_, kmeans_iter.score(X_test), silhouette_score(X_train, kmeans_iter.labels_)

(np.int32(2),
 array([-0.16050603, -0.72361306]),
 104.44216577761102,
 -33.19362229769065,
 np.float64(0.35665508838880466))