# Laboratory 7 – Exercises


## Exercise 1

Create tensors of the following ranks: 1, 2, and 3. Use values between 0 and 1 to fill your tensors. The size of the tensors can be defined as you wish, given that the ranks are created correctly. Print the shape of each of the tensors using the shape property.


In [ ]:
import torch

t1 = torch.rand(3)
t2 = torch.rand(2, 3)
t3 = torch.rand(2, 3, 4)

print(t1.shape)
print(t2.shape)
print(t3.shape)

torch.Size([3])
torch.Size([2, 3])
torch.Size([2, 3, 4])


## Exercise 2

The sigmoid activation function is an essential function in neural networks and is defined as follows:

$$sigmoid(x) = \frac{1}{1 + e^{-x}}$$

Take the derivative of this function with respect to x, where x = [-10, 10, 8].


In [ ]:
def sigmoid(x):
    return 1 / (1 + torch.exp(-x))


x = torch.tensor([-10.0, 10.0, 8.0], requires_grad=True)

y = sigmoid(x)

y.backward(torch.ones_like(x))

print("Derivative of sigmoid at x = ", x, " is ", x.grad)

Derivative of sigmoid at x =  tensor([-10.,  10.,   8.], requires_grad=True)  is  tensor([4.5396e-05, 4.5396e-05, 3.3524e-04])


## Exercise 3

Define the following two matrices:

$$A = \begin{bmatrix} 1 & 2 & -3 \\ 4 & 5 & 10 \end{bmatrix}$$

$$B = \begin{bmatrix} 10 & 11 & -2 \\ 13 & -3 & 8 \end{bmatrix}$$

• calculate the Hadamard product of the two matrices;
• add the scalar a = 10 to each element of matrix B;
• print the transpose of both matrices.


In [24]:
A = torch.tensor([[1, 2, -3], [4, 5, 10]])
B = torch.tensor([[10, 11, -2], [13, -3, 8]])

hadamard_product = A * B
B_added = B + 10
print(hadamard_product)
print(B_added)
print(A.T)
print(B.T)

tensor([[ 10,  22,   6],
        [ 52, -15,  80]])
tensor([[20, 21,  8],
        [23,  7, 18]])
tensor([[ 1,  4],
        [ 2,  5],
        [-3, 10]])
tensor([[10, 13],
        [11, -3],
        [-2,  8]])


## Exercise 4

Create the following two matrices:

$$A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}$$

$$B = \begin{bmatrix} 10 & 11 \\ -2 & 0 \\ 1 & -3 \end{bmatrix}$$

Multiply the two matrices and compute the Frobenius norm of A and B.


In [29]:
A = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
B = torch.tensor([[10, 11], [-2, 0], [1, -3]], dtype=torch.float32)

product = A @ B

fro_norm_A = torch.norm(A, p="fro")
fro_norm_B = torch.norm(B, p="fro")

print(product)
print(fro_norm_A.item())
print(fro_norm_B.item())

tensor([[ 9.,  2.],
        [36., 26.]])
9.539392471313477
15.329710006713867
