## Exercise 1: NumPy Array Indexing and Slicing

Create a random NumPy array of five rows and four columns. Using array indexing and slicing, display the items from row three to end and column two to end.

In [ ]:
import numpy as np

array = np.random.rand(5, 4)

print(array)
print(array[2:])
print(array[:, 1:])

[[0.24767405 0.16797149 0.7767208  0.75894776]
 [0.94502335 0.58498388 0.93503911 0.19002114]
 [0.34746507 0.47360773 0.82004403 0.02757999]
 [0.37636016 0.99852953 0.47862848 0.9156613 ]
 [0.07201119 0.51204357 0.49938283 0.13664676]]
[[0.34746507 0.47360773 0.82004403 0.02757999]
 [0.37636016 0.99852953 0.47862848 0.9156613 ]
 [0.07201119 0.51204357 0.49938283 0.13664676]]
[[0.16797149 0.7767208  0.75894776]
 [0.58498388 0.93503911 0.19002114]
 [0.47360773 0.82004403 0.02757999]
 [0.99852953 0.47862848 0.9156613 ]
 [0.51204357 0.49938283 0.13664676]]


## Exercise 2: Perfect Number Function

An integer, _n_, is said to be _perfect_ when the sum of all of the proper divisors of _n_ is equal to _n_. For example, 28 is a perfect number because its proper divisors are 1, 2, 4, 7 and 14, and 1+2+4+7+14=28.

Write a function that determines whether or not a positive integer is perfect. Your function will take one parameter. If that parameter is a perfect number then your function will return True, otherwise it will return False.

In [ ]:
def is_perfect(n):
    sum = 0

    for i in range(1, n):
        if n % i == 0:
            sum += i

    return sum == n


print(is_perfect(28))
print(is_perfect(29))

True
False


## Exercise 3: Text Formatting Class

Create a class with the following methods:

- Constructor (`__init__`) – This method should take the argument `text`, make it lower case, and remove all punctuation. Assume only the following punctuation is used: period, exclamation mark, comma and question mark. Assign this newly formatted text to a new attribute called `fmtText`.
- `strLength` – This method should return the length of the text.

In [ ]:
class MyClass:
    def __init__(self, text):
        self.fmtText = (
            text.lower()
            .replace(".", "")
            .replace("!", "")
            .replace(",", "")
            .replace("?", "")
        )

    def strLength(self):
        return len(self.fmtText)


obj = MyClass("Hello, World!")
print(obj.strLength())
print(obj.fmtText)

11
hello world
